
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # config.vm.provision "shell", inline: "echo Hello"
     config.vm.define "web" do |web|
      web.vm.box = "bento/ubuntu-20.04"
      web.vm.hostname = "web.example.com"
      web.vm.network "private_network", ip: "192.168.95.110"
      web.vm.provider "virtualbox" do |v|
        v.name = "web1"
        v.memory = 1024
        v.cpus = 2
      end
    end
      config.vm.define "db" do |db|
        db.vm.box = "bento/ubuntu-20.04"
        db.vm.hostname = "db.example.com"
        db.vm.network "private_network", ip: "192.168.95.120"
        db.vm.provider "virtualbox" do |v|
          v.name = "db"
          v.memory = 1024
          v.cpus = 2
        end   
      end
    end
