# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # config.vm.provision "shell", inline: "echo Hello"
     (1..3).each do |i|
     config.vm.define "web-#{i}" do |web|
      web.vm.box = "bento/ubuntu-20.04"
      web.vm.hostname = "web.example.com"
      web.vm.network "private_network", ip: "192.168.95.11#{i}"
      web.vm.provider "virtualbox" do |v|
        v.name = "web-#{1}"
        v.memory = 1024
        v.cpus = 2
      end
    end
    end
