# Specify the provider (e.g. VirtualBox)
Vagrant.configure("2") do |config|

  # Configure the master node
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/trusty64"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.50.10"
  end

  # Configure the server nodes
  (1..5).each do |i|
    config.vm.define "server#{i}" do |server|
      server.vm.box = "ubuntu/trusty64"
      server.vm.hostname = "server#{i}"
      server.vm.network "private_network", ip: "192.168.50.1#{i}"
    end
  end
end
